"""add_user_profiling_fields

Revision ID: 83a9a53f9434
Revises: cba124f19390
Create Date: 2026-03-15 19:39:55.496673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a9a53f9434'
down_revision: Union[str, None] = 'cba124f19390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('main_intent', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('daily_rhythm', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('commitment_level', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'commitment_level')
    op.drop_column('users', 'daily_rhythm')
    op.drop_column('users', 'main_intent')
    # ### end Alembic commands ###
