"""add_chests_table

Revision ID: 86380e609bea
Revises: 30c1d2cf0c4b
Create Date: 2026-03-15 17:32:34.411470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86380e609bea'
down_revision: Union[str, None] = '30c1d2cf0c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('rarity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('loot_data', sa.Text(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chests_status'), 'chests', ['status'], unique=False)
    op.create_index(op.f('ix_chests_user_id'), 'chests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chests_user_id'), table_name='chests')
    op.drop_index(op.f('ix_chests_status'), table_name='chests')
    op.drop_table('chests')
    # ### end Alembic commands ###
