"""create streaks table

Revision ID: fc39aeeb978e
Revises: 1de457736067
Create Date: 2026-03-15 14:38:31.607595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc39aeeb978e'
down_revision: Union[str, None] = '1de457736067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streaks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('current_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('best_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'type', name='uq_streaks_user_type')
    )
    op.create_index(op.f('ix_streaks_user_id'), 'streaks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streaks_user_id'), table_name='streaks')
    op.drop_table('streaks')
    # ### end Alembic commands ###
